export default function TermsPage() {
  return (
    <main className="min-h-screen bg-brand-bg px-4 py-8 max-w-2xl mx-auto">
      <a href="/settings" className="text-brand-primary text-sm mb-6 block">← Back</a>
      <h1 className="text-2xl font-bold text-gray-900 mb-6">Terms of Service</h1>
      <div className="space-y-4 text-sm text-gray-700">

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-gray-900">1. Service Description</h2>
          <p>
            Inburgering App provides KNM civic integration exam preparation tools including
            practice exams, AI-powered explanations, and progress tracking. The app is operated
            by Inburgering App BV, Rotterdam, Netherlands.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-gray-900">2. Subscription & Payments</h2>
          <ul className="list-disc ps-5 space-y-1">
            <li>Free tier: 1 practice exam, limited features</li>
            <li>Premium: €9.99/month, billed monthly, cancel anytime</li>
            <li>3-day free trial available for new subscribers</li>
            <li>Payments processed by Stripe (web) or Apple/Google (mobile)</li>
            <li>No refunds for partial months unless required by EU consumer law</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-gray-900">3. Acceptable Use</h2>
          <ul className="list-disc ps-5 space-y-1">
            <li>One account per person</li>
            <li>Maximum 3 active devices per account</li>
            <li>Do not attempt to extract exam answers through automated means</li>
            <li>Do not share your account with others</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-gray-900">4. AI Features</h2>
          <p>
            AI explanations are generated by OpenAI GPT-4o-mini and are for educational
            purposes only. They do not guarantee exam success. AI features require separate
            consent and are only available to Premium subscribers.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-gray-900">5. Disclaimer</h2>
          <p>
            This app is an independent study tool and is not affiliated with DUO
            (Dienst Uitvoering Onderwijs) or the Dutch government. Exam content is based
            on publicly available KNM materials and may not reflect the exact questions
            on the official exam.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-gray-900">6. Governing Law</h2>
          <p>
            These terms are governed by Dutch law. Disputes shall be submitted to the
            competent court in Rotterdam, Netherlands.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-gray-900">7. Contact</h2>
          <p>legal@inburgering.app</p>
        </section>

        <p className="text-xs text-gray-400 pt-4">Last updated: March 2026</p>
      </div>
    </main>
  );
}
